id = "iceberg-light-theme"
name = "Iceberg Light"
version = "0.1.0"
schema_version = 1
authors = ["ytseis"]
description = "Iceberg Light theme for Zed"
repository = "https://github.com/ytseis/iceberg-light-zed"